---
# playbook to set up docker swarm on rockylinux machines

#- gather_facts: false
- hosts: all
  become: yes

  tasks:

  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/dnf_module.html
  - name: Install dependencies
    dnf:
        name: "{{ item }}"
        state: latest
    with_items:
    - dnf-utils
    - device-mapper-persistent-data
    - lvm2
    - device-mapper-event 
    - device-mapper-libs 
    - device-mapper-event-libs

  # adding a yum repo should make it available for dnf
  - name: Add Docker repo
    yum_repository:
      name: docker_ce
      description: Docker CE Repo
      baseurl: https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install Docker
    dnf:
      name: "{{ item }}"
      state: latest
    with_items:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io

  - name: Start Docker service
    service:
      name: docker
      state: started
      enabled: yes
    
  - name: Add vagrant to docker group
    user:
        name: vagrant
        groups: docker
        append: yes
